services:
  python:
    build:
      context: .
      dockerfile: Dockerfile.python
    command: ollama serve
    environment:
      HOST_UID: ${HOST_UID:-1000}
      HOST_GID: ${HOST_GID:-1000}
    platform: linux/amd64
    volumes:
      - .:/workspace

  python-gpu:
    build:
      context: .
      dockerfile: Dockerfile.python-gpu
    command: ollama serve
    environment:
      HOST_UID: ${HOST_UID:-1000}
      HOST_GID: ${HOST_GID:-1000}
    platform: linux/amd64
    gpus: all
    volumes:
      - .:/workspace

  android:
    build:
      context: .
      dockerfile: Dockerfile.android
    platform: linux/amd64
    volumes:
      - .:/workspace

  native:
    build:
      context: .
      dockerfile: Dockerfile.native
    platform: linux/amd64
    volumes:
      - .:/workspace
